application:
  name: Dashboard IMU
  environment: ${ENVIRONMENT}
  database:
    host: ${DATABASE_HOST}
    name: ${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  frontend:
    url: ${FRONT_END_URL}
  security:
    token: ${SECURITY_TOKEN}

quarkus:
  package:
    jar:
      type: fast-jar
  devservices:
    enabled: false
  live-reload:
    instrumentation: true
  analytics:
    disabled: true
  swagger-ui:
    always-include: true
    path: /swagger-ui
  smallrye-openapi:
    path: /openapi
  http:
    port: 9000
    cors:
      ~: true
      origins: "*"
    record-request-start-time: true
    limits:
      max-body-size: 100M
    access-log:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %bbytes %Dms'
  hibernate-orm:
    unsupported-properties:
      "hibernate.order_inserts": true
    log:
      sql: false
    datasource: "<default>"
    database:
      generation: update
    implicit-naming-strategy: com.rot.core.hibernate.implementation.ImplicitNamingStrategyImpl
    second-level-caching-enabled: false
  datasource:
    devservices:
      enabled: false
    jdbc:
      idle-removal-interval: 50M
      max-lifetime: 50M
      max-size: 500
      leak-detection-interval: 8000
      url: jdbc:postgresql://${application.database.host}/${application.database.name}?autoReconnect=true&useSSL=false
    username: ${application.database.username}
    password: ${application.database.password}
    db-kind: postgresql
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: "1"
  locales: pt-BR
#  debug:
#    port: 5007
#    enable: true