application:
  name: Dashboard IMU
  environment: ${ENVIRONMENT:production}
  database:
    host: ${DATABASE_HOST:localhost}
    name: ${DATABASE_NAME:dashboard-imu}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1}
    port: ${DATABASE_PORT:5432}
  frontend:
    url: ${FRONTEND_URL:"http://localhost:8080"}
  backend:
    host: ${BACKEND_HOST:0.0.0.0}
    port: ${BACKEND_PORT:8000}
    protocol: ${BACKEND_PROTOCOL:http}
  security:
    issuer: ${SECURITY_ISSUER:dashboard-imu}
    token: ${SECURITY_TOKEN:1}
    subject: ${SECURITY_ISSUER:dashboard-imu}
  socket:
    host: ${SOCKET_HOST:localhost}
    port: ${SOCKET_PORT:8001}
  mqtt:
    host: ${MQTT_HOST:localhost}
    port: ${MQTT_PORT:8002}
  mdns:
    protocol: ${MDNS_PROTOCOL:http}
    name: ${MDNS_NAME:dashboard}

smallrye:
  jwt:
    sign:
      key:
        location: classpath:security/private.pem
mp:
  jwt:
    verify:
      publickey:
        location: classpath:security/public.pem
      issuer: ${application.security.issuer}

quarkus:
  application:
    name: ${application.mdns.name}
  mdns:
    enabled: true
  native:
    resources:
      includes: public.pem
  package:
    jar:
      type: fast-jar
  devservices:
    enabled: false
  live-reload:
    instrumentation: true
  analytics:
    disabled: true
  http:
    #    host: ${application.backend.host}
    port: ${application.backend.port}
    cors:
      ~: true
      origins: "*"
    record-request-start-time: true
    limits:
      max-body-size: 100M
    access-log:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %bbytes %Dms'
  hibernate-orm:
    log:
      sql: false
    jdbc:
      timezone: America/Sao_Paulo
    database:
      generation: update
    packages: com.rot, com.blazebit.persistence.impl.function.entity
    implicit-naming-strategy: com.rot.core.hibernate.implementation.ImplicitNamingStrategyImpl
    second-level-caching-enabled: false
  datasource:
    username: ${application.database.username}
    password: ${application.database.password}
    db-kind: postgresql
    devservices:
      enabled: false
    jdbc:
      idle-removal-interval: 50M
      max-lifetime: 50M
      max-size: 500
      leak-detection-interval: 8000
      url: jdbc:postgresql://${application.database.host}:${application.database.port}/${application.database.name}?autoReconnect=true&useSSL=false
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: "1"
  locales: pt-BR
  smallrye-jwt:
    enabled: true
  config:
    locations: application.dev.yml,application.yml