application:
  name: Dashboard IMU
  environment: ${ENVIRONMENT}
  database:
    host: ${DATABASE_HOST}
    name: ${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  frontend:
    url: ${FRONTEND_URL}
  backend:
    host: ${BACKEND_HOST:0.0.0.0}
    port: ${BACKEND_PORT:8000}
    protocol: ${BACKEND_PROTOCOL}
  security:
    issuer: ${SECURITY_ISSUER:dashboard-imu}
    token: ${SECURITY_TOKEN}
    subject: ${SECURITY_ISSUER:dashboard-imu}
  socket:
    host: ${SOCKET_HOST}
    port: ${SOCKET_PORT:8001}
  mqtt:
    host: ${MQTT_HOST}
    port: ${MQTT_PORT:8002}
  mdns:
    protocol: ${MDNS_PROTOCOL:http}
    name: ${MDNS_NAME:dashboard}

smallrye:
  jwt:
    sign:
      key:
        location: classpath:META-INF/resources/security/private.pem
mp:
  jwt:
    verify:
      publickey:
        location: classpath:META-INF/resources/security/public.pem
      issuer: ${application.security.issuer}

quarkus:
  application:
    name: ${application.mdns.name}
#    host: ${application.backend.host}
  mdns:
    enabled: true
  native:
    resources:
      includes: public.pem
  package:
    jar:
      type: fast-jar
  devservices:
    enabled: false
  live-reload:
    instrumentation: true
  analytics:
    disabled: true
#  swagger-ui:
#    always-include: true
#    path: /api/swagger-ui
#  smallrye-openapi:
#    path: /api/openapi
  http:
#    host: ${application.backend.host}
    port: ${application.backend.port}
    cors:
      ~: true
      origins: "*"
    record-request-start-time: true
    limits:
      max-body-size: 100M
    access-log:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %bbytes %Dms'
  hibernate-orm:
    log:
      sql: false
    datasource: "<default>"
    database:
      generation: update
    implicit-naming-strategy: com.rot.core.hibernate.implementation.ImplicitNamingStrategyImpl
    second-level-caching-enabled: false
  datasource:
    devservices:
      enabled: false
    jdbc:
      idle-removal-interval: 50M
      max-lifetime: 50M
      max-size: 500
      leak-detection-interval: 8000
      url: jdbc:postgresql://${application.database.host}/${application.database.name}?autoReconnect=true&useSSL=false
    username: ${application.database.username}
    password: ${application.database.password}
    db-kind: postgresql
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: "1"
  locales: pt-BR
  smallrye-jwt:
    enabled: true
  config:
    locations: application.yml,application.base.yml